# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import gerenciador_pb2 as gerenciador__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in gerenciador_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AlunoServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListAlunos = channel.unary_unary(
                '/gerenciador.AlunoService/ListAlunos',
                request_serializer=gerenciador__pb2.Empty.SerializeToString,
                response_deserializer=gerenciador__pb2.AlunosList.FromString,
                _registered_method=True)
        self.GetAluno = channel.unary_unary(
                '/gerenciador.AlunoService/GetAluno',
                request_serializer=gerenciador__pb2.AlunoId.SerializeToString,
                response_deserializer=gerenciador__pb2.Aluno.FromString,
                _registered_method=True)
        self.CreateAluno = channel.unary_unary(
                '/gerenciador.AlunoService/CreateAluno',
                request_serializer=gerenciador__pb2.Aluno.SerializeToString,
                response_deserializer=gerenciador__pb2.AlunoId.FromString,
                _registered_method=True)
        self.UpdateAluno = channel.unary_unary(
                '/gerenciador.AlunoService/UpdateAluno',
                request_serializer=gerenciador__pb2.Aluno.SerializeToString,
                response_deserializer=gerenciador__pb2.Empty.FromString,
                _registered_method=True)
        self.DeleteAluno = channel.unary_unary(
                '/gerenciador.AlunoService/DeleteAluno',
                request_serializer=gerenciador__pb2.AlunoId.SerializeToString,
                response_deserializer=gerenciador__pb2.Empty.FromString,
                _registered_method=True)


class AlunoServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListAlunos(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAluno(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateAluno(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateAluno(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteAluno(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AlunoServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListAlunos': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAlunos,
                    request_deserializer=gerenciador__pb2.Empty.FromString,
                    response_serializer=gerenciador__pb2.AlunosList.SerializeToString,
            ),
            'GetAluno': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAluno,
                    request_deserializer=gerenciador__pb2.AlunoId.FromString,
                    response_serializer=gerenciador__pb2.Aluno.SerializeToString,
            ),
            'CreateAluno': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateAluno,
                    request_deserializer=gerenciador__pb2.Aluno.FromString,
                    response_serializer=gerenciador__pb2.AlunoId.SerializeToString,
            ),
            'UpdateAluno': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateAluno,
                    request_deserializer=gerenciador__pb2.Aluno.FromString,
                    response_serializer=gerenciador__pb2.Empty.SerializeToString,
            ),
            'DeleteAluno': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteAluno,
                    request_deserializer=gerenciador__pb2.AlunoId.FromString,
                    response_serializer=gerenciador__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'gerenciador.AlunoService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('gerenciador.AlunoService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AlunoService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListAlunos(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gerenciador.AlunoService/ListAlunos',
            gerenciador__pb2.Empty.SerializeToString,
            gerenciador__pb2.AlunosList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAluno(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gerenciador.AlunoService/GetAluno',
            gerenciador__pb2.AlunoId.SerializeToString,
            gerenciador__pb2.Aluno.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateAluno(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gerenciador.AlunoService/CreateAluno',
            gerenciador__pb2.Aluno.SerializeToString,
            gerenciador__pb2.AlunoId.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateAluno(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gerenciador.AlunoService/UpdateAluno',
            gerenciador__pb2.Aluno.SerializeToString,
            gerenciador__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteAluno(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gerenciador.AlunoService/DeleteAluno',
            gerenciador__pb2.AlunoId.SerializeToString,
            gerenciador__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ProfessorServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListProfessores = channel.unary_unary(
                '/gerenciador.ProfessorService/ListProfessores',
                request_serializer=gerenciador__pb2.Empty.SerializeToString,
                response_deserializer=gerenciador__pb2.ProfessoresList.FromString,
                _registered_method=True)
        self.GetProfessor = channel.unary_unary(
                '/gerenciador.ProfessorService/GetProfessor',
                request_serializer=gerenciador__pb2.ProfessorId.SerializeToString,
                response_deserializer=gerenciador__pb2.Professor.FromString,
                _registered_method=True)
        self.CreateProfessor = channel.unary_unary(
                '/gerenciador.ProfessorService/CreateProfessor',
                request_serializer=gerenciador__pb2.Professor.SerializeToString,
                response_deserializer=gerenciador__pb2.ProfessorId.FromString,
                _registered_method=True)
        self.UpdateProfessor = channel.unary_unary(
                '/gerenciador.ProfessorService/UpdateProfessor',
                request_serializer=gerenciador__pb2.Professor.SerializeToString,
                response_deserializer=gerenciador__pb2.Empty.FromString,
                _registered_method=True)
        self.DeleteProfessor = channel.unary_unary(
                '/gerenciador.ProfessorService/DeleteProfessor',
                request_serializer=gerenciador__pb2.ProfessorId.SerializeToString,
                response_deserializer=gerenciador__pb2.Empty.FromString,
                _registered_method=True)


class ProfessorServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListProfessores(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProfessor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateProfessor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateProfessor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteProfessor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProfessorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListProfessores': grpc.unary_unary_rpc_method_handler(
                    servicer.ListProfessores,
                    request_deserializer=gerenciador__pb2.Empty.FromString,
                    response_serializer=gerenciador__pb2.ProfessoresList.SerializeToString,
            ),
            'GetProfessor': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProfessor,
                    request_deserializer=gerenciador__pb2.ProfessorId.FromString,
                    response_serializer=gerenciador__pb2.Professor.SerializeToString,
            ),
            'CreateProfessor': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateProfessor,
                    request_deserializer=gerenciador__pb2.Professor.FromString,
                    response_serializer=gerenciador__pb2.ProfessorId.SerializeToString,
            ),
            'UpdateProfessor': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateProfessor,
                    request_deserializer=gerenciador__pb2.Professor.FromString,
                    response_serializer=gerenciador__pb2.Empty.SerializeToString,
            ),
            'DeleteProfessor': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteProfessor,
                    request_deserializer=gerenciador__pb2.ProfessorId.FromString,
                    response_serializer=gerenciador__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'gerenciador.ProfessorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('gerenciador.ProfessorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ProfessorService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListProfessores(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gerenciador.ProfessorService/ListProfessores',
            gerenciador__pb2.Empty.SerializeToString,
            gerenciador__pb2.ProfessoresList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProfessor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gerenciador.ProfessorService/GetProfessor',
            gerenciador__pb2.ProfessorId.SerializeToString,
            gerenciador__pb2.Professor.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateProfessor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gerenciador.ProfessorService/CreateProfessor',
            gerenciador__pb2.Professor.SerializeToString,
            gerenciador__pb2.ProfessorId.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateProfessor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gerenciador.ProfessorService/UpdateProfessor',
            gerenciador__pb2.Professor.SerializeToString,
            gerenciador__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteProfessor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gerenciador.ProfessorService/DeleteProfessor',
            gerenciador__pb2.ProfessorId.SerializeToString,
            gerenciador__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class MateriaServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListMaterias = channel.unary_unary(
                '/gerenciador.MateriaService/ListMaterias',
                request_serializer=gerenciador__pb2.Empty.SerializeToString,
                response_deserializer=gerenciador__pb2.MateriasList.FromString,
                _registered_method=True)
        self.GetMateria = channel.unary_unary(
                '/gerenciador.MateriaService/GetMateria',
                request_serializer=gerenciador__pb2.MateriaId.SerializeToString,
                response_deserializer=gerenciador__pb2.Materia.FromString,
                _registered_method=True)
        self.CreateMateria = channel.unary_unary(
                '/gerenciador.MateriaService/CreateMateria',
                request_serializer=gerenciador__pb2.Materia.SerializeToString,
                response_deserializer=gerenciador__pb2.MateriaId.FromString,
                _registered_method=True)
        self.UpdateMateria = channel.unary_unary(
                '/gerenciador.MateriaService/UpdateMateria',
                request_serializer=gerenciador__pb2.Materia.SerializeToString,
                response_deserializer=gerenciador__pb2.Empty.FromString,
                _registered_method=True)
        self.DeleteMateria = channel.unary_unary(
                '/gerenciador.MateriaService/DeleteMateria',
                request_serializer=gerenciador__pb2.MateriaId.SerializeToString,
                response_deserializer=gerenciador__pb2.Empty.FromString,
                _registered_method=True)


class MateriaServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListMaterias(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMateria(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateMateria(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateMateria(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteMateria(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MateriaServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListMaterias': grpc.unary_unary_rpc_method_handler(
                    servicer.ListMaterias,
                    request_deserializer=gerenciador__pb2.Empty.FromString,
                    response_serializer=gerenciador__pb2.MateriasList.SerializeToString,
            ),
            'GetMateria': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMateria,
                    request_deserializer=gerenciador__pb2.MateriaId.FromString,
                    response_serializer=gerenciador__pb2.Materia.SerializeToString,
            ),
            'CreateMateria': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateMateria,
                    request_deserializer=gerenciador__pb2.Materia.FromString,
                    response_serializer=gerenciador__pb2.MateriaId.SerializeToString,
            ),
            'UpdateMateria': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateMateria,
                    request_deserializer=gerenciador__pb2.Materia.FromString,
                    response_serializer=gerenciador__pb2.Empty.SerializeToString,
            ),
            'DeleteMateria': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteMateria,
                    request_deserializer=gerenciador__pb2.MateriaId.FromString,
                    response_serializer=gerenciador__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'gerenciador.MateriaService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('gerenciador.MateriaService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MateriaService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListMaterias(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gerenciador.MateriaService/ListMaterias',
            gerenciador__pb2.Empty.SerializeToString,
            gerenciador__pb2.MateriasList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMateria(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gerenciador.MateriaService/GetMateria',
            gerenciador__pb2.MateriaId.SerializeToString,
            gerenciador__pb2.Materia.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateMateria(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gerenciador.MateriaService/CreateMateria',
            gerenciador__pb2.Materia.SerializeToString,
            gerenciador__pb2.MateriaId.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateMateria(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gerenciador.MateriaService/UpdateMateria',
            gerenciador__pb2.Materia.SerializeToString,
            gerenciador__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteMateria(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gerenciador.MateriaService/DeleteMateria',
            gerenciador__pb2.MateriaId.SerializeToString,
            gerenciador__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class TurmaServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListTurmas = channel.unary_unary(
                '/gerenciador.TurmaService/ListTurmas',
                request_serializer=gerenciador__pb2.Empty.SerializeToString,
                response_deserializer=gerenciador__pb2.TurmasList.FromString,
                _registered_method=True)
        self.GetTurma = channel.unary_unary(
                '/gerenciador.TurmaService/GetTurma',
                request_serializer=gerenciador__pb2.TurmaId.SerializeToString,
                response_deserializer=gerenciador__pb2.Turma.FromString,
                _registered_method=True)
        self.CreateTurma = channel.unary_unary(
                '/gerenciador.TurmaService/CreateTurma',
                request_serializer=gerenciador__pb2.Turma.SerializeToString,
                response_deserializer=gerenciador__pb2.TurmaId.FromString,
                _registered_method=True)
        self.UpdateTurma = channel.unary_unary(
                '/gerenciador.TurmaService/UpdateTurma',
                request_serializer=gerenciador__pb2.Turma.SerializeToString,
                response_deserializer=gerenciador__pb2.Empty.FromString,
                _registered_method=True)
        self.DeleteTurma = channel.unary_unary(
                '/gerenciador.TurmaService/DeleteTurma',
                request_serializer=gerenciador__pb2.TurmaId.SerializeToString,
                response_deserializer=gerenciador__pb2.Empty.FromString,
                _registered_method=True)


class TurmaServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListTurmas(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTurma(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateTurma(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateTurma(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteTurma(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TurmaServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListTurmas': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTurmas,
                    request_deserializer=gerenciador__pb2.Empty.FromString,
                    response_serializer=gerenciador__pb2.TurmasList.SerializeToString,
            ),
            'GetTurma': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTurma,
                    request_deserializer=gerenciador__pb2.TurmaId.FromString,
                    response_serializer=gerenciador__pb2.Turma.SerializeToString,
            ),
            'CreateTurma': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateTurma,
                    request_deserializer=gerenciador__pb2.Turma.FromString,
                    response_serializer=gerenciador__pb2.TurmaId.SerializeToString,
            ),
            'UpdateTurma': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateTurma,
                    request_deserializer=gerenciador__pb2.Turma.FromString,
                    response_serializer=gerenciador__pb2.Empty.SerializeToString,
            ),
            'DeleteTurma': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteTurma,
                    request_deserializer=gerenciador__pb2.TurmaId.FromString,
                    response_serializer=gerenciador__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'gerenciador.TurmaService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('gerenciador.TurmaService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TurmaService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListTurmas(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gerenciador.TurmaService/ListTurmas',
            gerenciador__pb2.Empty.SerializeToString,
            gerenciador__pb2.TurmasList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTurma(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gerenciador.TurmaService/GetTurma',
            gerenciador__pb2.TurmaId.SerializeToString,
            gerenciador__pb2.Turma.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateTurma(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gerenciador.TurmaService/CreateTurma',
            gerenciador__pb2.Turma.SerializeToString,
            gerenciador__pb2.TurmaId.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateTurma(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gerenciador.TurmaService/UpdateTurma',
            gerenciador__pb2.Turma.SerializeToString,
            gerenciador__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteTurma(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gerenciador.TurmaService/DeleteTurma',
            gerenciador__pb2.TurmaId.SerializeToString,
            gerenciador__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
